name: RCBHC
favicon: null
layout_spectrum: 0.73193
typography_spectrum: 0.19540455704554915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010000'
    - '#670003'
    - '#a57b6b'
    - '#8f4a23'
  brandStrength: 0.2655687998048961
  lightness: 0.17204535473138094
  saturation: 0.005595204886049032
  rhythmicContrast: 0.7397863646037877
purpose: []
